[build-system]
requires = [
    "setuptools >=44",
    "wheel >=0.36",
    "cmake",
]
build-backend = "setuptools.build_meta"

[project]
name = "equistore"
description = "A specialized data storage format suited to atomistic machine learning needs and more."
readme = "README.rst"
requires-python = ">=3.6"

dependencies = [
    "numpy>=1.20.0",
]
dynamic = ["version"]

[tool.setuptools.packages.find]
where = ["python/src"]

[tool.isort]
profile = "black"
line_length = 88
indent = 4
include_trailing_comma = true
lines_after_imports = 2
known_first_party = "equistore"
