[package]
name = "metatensor"
version = "0.1.3"
edition = "2021"
rust-version = "1.65"

description = "Self-describing sparse tensor data format for atomistic machine learning and beyond"
readme = "../../README.md"
homepage = "https://lab-cosmo.github.io/metatensor/latest/"
repository = "https://github.com/lab-cosmo/metatensor"
license = "BSD-3-Clause"

[lib]
bench = false

[dependencies]
metatensor-sys = {version = "0.1.3", path="../metatensor-sys"}

once_cell = "1"
smallvec = {version = "1", features = ["union"]}
ndarray = {version = "0.15"}
rayon = {version = "1", optional = true}


[features]
default = []
# use the static build of metatensor-core instead of the shared one
static = ["metatensor-sys/static"]
