[package]
name = "metatensor-core"
version = "0.1.4"
edition = "2021"
publish = false
rust-version = "1.65"
exclude = [
    "tests"
]

[lib]
crate-type = ["cdylib", "staticlib"]
name = "metatensor"
bench = false

[dependencies]
ahash = "=0.8.7"  # last version supporting rustc 1.65
hashbrown = "0.14"
indexmap = "2"
once_cell = "1"
smallvec = {version = "1", features = ["union"]}

# implementation of the NPZ serialization format
byteorder = {version = "1"}
num-traits = {version = "0.2", default-features = false}
zip = {version = "0.6", default-features = false}

[build-dependencies]
cbindgen = { version = "0.26", default-features = false }

[dev-dependencies]
which = "5"
lazy_static = "1"

# This is the last version supporting rustc 1.65
home = "=0.5.5"
