[package]
name = "metatensor-python"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.65"

[lib]
path = "lib.rs"

[dev-dependencies]
which = "5"

# This is the last version supporting rustc 1.65
home = "=0.5.5"
